export const ADMIN_ROUTE = {
   ADMIN: 'admin',
   USERS: 'admin/users',
   USER_EDIT: 'admin/user/edit/:id',
   USER_ADD: 'admin/user/add',
   USER_VIEW: 'admin/user/:id',
   CATEGORIES: 'admin/categories',
   CATEGORY_EDIT: 'admin/category/edit/:id',
   CATEGORY_ADD: 'admin/category/add',
   CATEGORY_VIEW: 'admin/category/:id',
   BRANDS: 'admin/brands',
   BRAND_EDIT: 'admin/brand/edit/:id',
   BRAND_ADD: 'admin/brand/add',
   BRAND_VIEW: 'admin/brand/:id',
   PRODUCTS: 'admin/products',
   PRODUCT_EDIT: 'admin/product/edit/:id',
   PRODUCT_ADD: 'admin/product/add',
   PRODUCT_VIEW: 'admin/product/:id',
}
